### ISSUE TITLE
What kind of button are you using?

### ISSUE THREAD

**Issue by diversit** [nos86/node-red-contrib-shutter-controller#1]
Since Github has no way to reach out to a committer, I'm trying it this way.

I just looked into this shutter controller.
What kind of button are you using which supports short and long presses?
I have googled around a bit but cannot find such a button for node-red.
It would also be very useful for me since I connect to a KNX installation which also has these kind of buttons.

Regards

**Comment by nos86** [comment]
Hi @diversit,

I'm using a home-made IoT button: this button publish its status on MQTT topic.
Possible status are:
- Short (if you press the button for less than 800mS)
- Long (if you press the button for more than 800mS)
- Released (after a Long event, when the button is actually released)
- Double (if you do a fast double press)

This module uses those status to control the shutter:
- if short, it means I want to fully open/close the shutter
- if long, it move the shutter until "released" is received

How do you want to use it?

**Comment by diversit** [comment]
Hi Salvo,

Thanks for the reply.
Ah ... a hardware button. Makes sense.
Ideally I would like to use ui buttons which support long/short/double
press. I’ll have a chat with a friend who is a frontend guru to see if I
can fit that into a custom template.
Perhaps I could comply to your protocol so I can use your controller.

I had a go at it yesterday with multiple ui buttons and some functions but
that is not ideal.

Thanks again.
Joost
